#!/usr/bin/env bash
# Writes eval-jit.conf next to a haxe binary built from this tree, which turns the eval JIT on for
# that binary (HAXE-PLUS.md, "J: native JIT").
#
#   jit-conf.sh <directory of the haxe binary> <root of its build objects> [cache directory]
#
# Run it in the environment that built the binary (the same opam switch): the JIT compiles its
# units with that ocamlopt, against the interfaces and inlining data (.cmi/.cmx) under <objs root>,
# which must be the very files the binary was linked from (_build/default for ./haxe, the snapshot
# install.sh makes for an installed binary). The cache defaults to <bin dir>/jit-cache; a binary
# prunes the caches other builds left in the same directory once they are an hour old.
set -euo pipefail
BIN_DIR="$(cd "$1" && pwd)"
OBJS="$(cd "$2" && pwd)"
CACHE="${3:-$BIN_DIR/jit-cache}"
OCAMLOPT="$(command -v ocamlopt.opt || command -v ocamlopt)"
JOBS="$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 8)"
{
	echo "# generated by extra/haxe-plus/jit-conf.sh"
	echo "ocamlopt=$OCAMLOPT"
	echo "cache=$CACHE"
	echo "jobs=$JOBS"
	# The linear-scan allocator: much faster on the large functions units are made of.
	echo "flag=-linscan"
	find "$OBJS" -type d \( -name byte -o -name native \) -path "*objs*" | sort | sed 's/^/include=/'
	for p in extlib ptmap sha xml-light sedlex camlp-streams luv integers ctypes; do
		d="$(ocamlfind query "$p" 2>/dev/null || true)"
		if [ -n "$d" ]; then echo "include=$d"; fi
	done
	echo "include=$(ocamlc -where)/threads"
} > "$BIN_DIR/eval-jit.conf"
echo "wrote $BIN_DIR/eval-jit.conf"
